### ISSUE TITLE
How to handle links properly

### ISSUE THREAD

**Issue by f3rdy** [justmiles/go-markdown2confluence#18] opened 2020-06-19 08:44 UTC
Hi, thanks for the tool. At a first glance it looks promising and helpful.

I've got a structure like this in my project:

```
project_root/readme.md
project_root/documentation/do_this.md
project_root/documentation/do_that.md
```

I use the readme.md moreover to link to the subdocuments and use it primarily as an index or TOC file. From the subdocuments, I link back to the index or to other subdocuments. 

First problem I encounter is, that the the links between the project root directory and subdirectories are not translated into confluence pages/subpages and therefore do not work.

I think, I could flatten the structure to put the readme.md into the documentation subdirectory of the source code and just use the project root readme.md to link to the documentation/readme.md. That might do it.

A different case would be to have links to (other) source code files in my markdown. It would be cool to have a possibility to change relative links to local files at least by absolute links to the current repository. Sure, I can do that directly in the markdown, but wouldn't it be better to have this in the tooling?

Thanks,
ferdy

**Comment by justmiles** [comment] 2020-06-19 20:35
Duplicate of #9

**Closed** 2020-06-19 20:35 UTC
