### ISSUE TITLE
support API tokens

### ISSUE THREAD

**Issue by grexe** [justmiles/go-markdown2confluence#6] opened 2019-11-12 17:13 UTC
currently, you have to supply username and password for uploading pages.
It would be preferable to use API tokens here, as they can be managed per script and are safer to use, e..g can be revoked.

**Comment by justmiles** [comment] 2019-11-12 20:30
This is a dupe of #3. I'll leave this open until I update the README with instructions on how to use API tokens.

**Comment by justmiles** [comment] 2019-11-15 18:34
added to readme: https://github.com/justmiles/go-markdown2confluence/commit/1e62ed2b5051440d16174520a2e5c3c9efcc69de

**Closed by justmiles** 2019-11-15 18:34 UTC
